export const PHONES_LIST_REQUEST = "PHONES_LIST_REQUEST";
export const PHONES_LIST_SUCCESS = "PHONES_LIST_SUCCESS";
export const PHONES_LIST_FAIL = "PHONES_LIST_FAIL";

export const PHONES_CREATE_REQUEST = "PHONES_CREATE_REQUEST";
export const PHONES_CREATE_SUCCESS = "PHONES_CREATE_SUCCESS";
export const PHONES_CREATE_FAIL = "PHONES_CREATE_FAIL";

export const PHONES_UPDATE_REQUEST = "PHONES_UPDATE_REQUEST";
export const PHONES_UPDATE_SUCCESS = "PHONES_UPDATE_SUCCESS";
export const PHONES_UPDATE_FAIL = "PHONES_UPDATE_FAIL";

export const PHONES_DELETE_REQUEST = "PHONES_DELETE_REQUEST";
export const PHONES_DELETE_SUCCESS = "PHONES_DELETE_SUCCESS";
export const PHONES_DELETE_FAIL = "PHONES_DELETE_FAIL";
